import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, Filter, ArrowRight } from 'lucide-react';
import { useData } from '@/lib/DataContext';
import { RISK_COLORS, formatDate } from '@/lib/ui';
import type { RiskLevel } from '@/lib/types';

type AlertFilter = 'ALL' | RiskLevel;

export default function Alerts() {
  const { alerts, loading } = useData();
  const [filter, setFilter] = useState<AlertFilter>('ALL');

  const filtered = useMemo(() => {
    if (filter === 'ALL') return alerts;
    return alerts.filter((a) => a.level === filter);
  }, [alerts, filter]);

  const counts = useMemo(() => {
    const c: Record<string, number> = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
    for (const a of alerts) c[a.level]++;
    return c;
  }, [alerts]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <AlertTriangle className="w-8 h-8 text-[#0f4c5c] animate-pulse" />
      </div>
    );
  }

  return (
    <div className="p-8 max-w-5xl mx-auto animate-fade-in">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Early Warning Alerts</h1>
        <p className="text-sm text-gray-500 mt-1">
          {alerts.length} active alerts generated by the AI risk engine
        </p>
      </div>

      {/* Filter pills */}
      <div className="flex items-center gap-2 mb-6">
        <Filter className="w-4 h-4 text-gray-400" />
        {(['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as AlertFilter[]).map((level) => {
          const isActive = filter === level;
          const count = level === 'ALL' ? alerts.length : counts[level];
          const colors = level !== 'ALL' ? RISK_COLORS[level as RiskLevel] : null;
          return (
            <button
              key={level}
              onClick={() => setFilter(level)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all border ${
                isActive
                  ? colors
                    ? `${colors.bg} ${colors.text} ${colors.border}`
                    : 'bg-[#0f4c5c] text-white border-[#0f4c5c]'
                  : 'bg-white text-gray-500 border-gray-200 hover:bg-gray-50'
              }`}
            >
              {level === 'ALL' ? 'All Alerts' : level}
              <span className="ml-1.5 opacity-60">({count})</span>
            </button>
          );
        })}
      </div>

      {/* Alert list */}
      {filtered.length === 0 ? (
        <div className="card p-12 text-center">
          <div className="w-12 h-12 rounded-full bg-emerald-50 flex items-center justify-center mx-auto mb-3">
            <AlertTriangle className="w-6 h-6 text-emerald-500" />
          </div>
          <p className="text-sm text-gray-500">No alerts at this level.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((alert) => {
            const colors = RISK_COLORS[alert.level];
            return (
              <Link
                key={alert.id}
                to={`/projects/${alert.projectId}`}
                className="card p-5 flex items-start gap-4 hover:shadow-md transition-all group relative overflow-hidden"
              >
                <div
                  className="absolute inset-y-0 left-0 w-16 pointer-events-none"
                  style={{ background: `linear-gradient(to right, ${colors.hex}10, transparent)` }}
                />
                {/* Level indicator */}
                <div className={`w-10 h-10 rounded-lg ${colors.bg} flex items-center justify-center shrink-0`}>
                  <AlertTriangle className={`w-5 h-5 ${colors.text}`} strokeWidth={2.2} />
                </div>

                {/* Content */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2.5 mb-1">
                    <h3 className="text-sm font-semibold text-gray-900 group-hover:text-[#0f4c5c] transition-colors">
                      {alert.projectName}
                    </h3>
                    <span className={`badge ${colors.bg} ${colors.text} ${colors.border} text-[10px]`}>
                      {alert.level}
                    </span>
                  </div>
                  <p className="text-xs text-gray-400 mb-2">{alert.projectId} · {formatDate(alert.snapshotDate)}</p>

                  {/* Triggering factors */}
                  <div className="flex flex-wrap gap-2">
                    {alert.triggeringFactors.map((factor, i) => (
                      <span
                        key={i}
                        className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-medium bg-gray-50 text-gray-600 border border-gray-100"
                      >
                        {factor.feature}
                        <span className="text-gray-400 font-mono">{factor.value}</span>
                      </span>
                    ))}
                  </div>
                </div>

                <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-[#0f4c5c] transition-colors mt-2 shrink-0" />
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
