/*
# ProjectSaarthi AI — Core Schema

Creates the data layer for an AI-powered infrastructure project monitoring platform.
This stores synthetic project data modeled on publicly described PAIMANA/CUF fields.

1. New Tables
- `projects`: one row per infrastructure project (sector, ministry, agency, cost, dates, status, computed risk)
- `project_snapshots`: monthly time-series per project (cost, expenditure, progress, milestones, variance)
- `alerts`: early-warning alerts generated by the risk engine (level, triggers, date)
- `model_metrics`: persisted evaluation metrics from the ML training run (for the Methodology page)

2. Security
- Single-tenant app (no auth screen). RLS enabled on all tables.
- anon + authenticated CRUD enabled — data is intentionally public/shared for the monitoring dashboard.
*/

CREATE TABLE IF NOT EXISTS projects (
  id text PRIMARY KEY,
  name text NOT NULL,
  sector text NOT NULL,
  ministry text NOT NULL,
  implementing_agency text NOT NULL,
  state text NOT NULL,
  approved_cost_cr double precision NOT NULL,
  revised_cost_cr double precision NOT NULL,
  original_start_date date NOT NULL,
  original_completion_date date NOT NULL,
  revised_completion_date date,
  status text NOT NULL DEFAULT 'Ongoing',
  risk_score double precision NOT NULL DEFAULT 0,
  risk_level text NOT NULL DEFAULT 'LOW',
  cost_overrun_flag int NOT NULL DEFAULT 0,
  cost_overrun_pct double precision NOT NULL DEFAULT 0,
  time_overrun_flag int NOT NULL DEFAULT 0,
  delay_days int NOT NULL DEFAULT 0,
  shap_factors jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_projects" ON projects;
CREATE POLICY "anon_select_projects" ON projects FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_projects" ON projects;
CREATE POLICY "anon_insert_projects" ON projects FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_projects" ON projects;
CREATE POLICY "anon_update_projects" ON projects FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_projects" ON projects;
CREATE POLICY "anon_delete_projects" ON projects FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS project_snapshots (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  snapshot_date date NOT NULL,
  revised_cost_cr double precision NOT NULL,
  expenditure_cr double precision NOT NULL,
  physical_progress_pct double precision NOT NULL,
  financial_progress_pct double precision NOT NULL,
  milestones_total int NOT NULL,
  milestones_achieved int NOT NULL,
  milestones_delayed int NOT NULL,
  schedule_variance_days int NOT NULL,
  risk_score double precision NOT NULL DEFAULT 0,
  risk_level text NOT NULL DEFAULT 'LOW',
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_snapshots_project_id ON project_snapshots(project_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_date ON project_snapshots(snapshot_date);

ALTER TABLE project_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_snapshots" ON project_snapshots;
CREATE POLICY "anon_select_snapshots" ON project_snapshots FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_snapshots" ON project_snapshots;
CREATE POLICY "anon_insert_snapshots" ON project_snapshots FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_snapshots" ON project_snapshots;
CREATE POLICY "anon_delete_snapshots" ON project_snapshots FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS alerts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  project_name text NOT NULL,
  level text NOT NULL,
  triggering_factors jsonb NOT NULL DEFAULT '[]'::jsonb,
  snapshot_date date NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alerts_project_id ON alerts(project_id);
CREATE INDEX IF NOT EXISTS idx_alerts_level ON alerts(level);

ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_alerts" ON alerts;
CREATE POLICY "anon_select_alerts" ON alerts FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_alerts" ON alerts;
CREATE POLICY "anon_insert_alerts" ON alerts FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_alerts" ON alerts;
CREATE POLICY "anon_delete_alerts" ON alerts FOR DELETE
  TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS model_metrics (
  id text PRIMARY KEY,
  model_name text NOT NULL,
  task text NOT NULL,
  accuracy double precision,
  precision_score double precision,
  recall double precision,
  f1 double precision,
  roc_auc double precision,
  pr_auc double precision,
  mae double precision,
  rmse double precision,
  r2 double precision,
  lead_time_months double precision,
  is_baseline boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE model_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_model_metrics" ON model_metrics;
CREATE POLICY "anon_select_model_metrics" ON model_metrics FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_model_metrics" ON model_metrics;
CREATE POLICY "anon_insert_model_metrics" ON model_metrics FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_model_metrics" ON model_metrics;
CREATE POLICY "anon_delete_model_metrics" ON model_metrics FOR DELETE
  TO anon, authenticated USING (true);
